import java.util.Scanner;

class Num extends Exception{
	Num(){
		super("잘못된 값!!!!!");	//Exception(부모)생성자 호출 ->Exception(String message)
	}
}
public class Ex_Throw {
	static int in() throws Num{	//함수에서 처리안하고 Num클래스에서 처리할게...	
		//throws IOException 했던거 기억하기!!
		Scanner s=new Scanner(System.in);
		int n=s.nextInt();
		if(n<0) {
			Num num=new Num();	//생성자 호출
			throw num;	//에러를 던지겠다.
		}
		return n; 
	}
	public static void main(String[] args) {
		System.out.println("양수 입력");
		try {
			int n = in(); // 정수 입력하는 함수
			System.out.println(n);
		} 
		catch (Exception e) {
			System.out.println(e.getMessage());	//super("잘못된 값!!!!!");를 처리하고 있다.
		}
	}
}
